### ISSUE TITLE
Can't use local ipfs node

### ISSUE THREAD

**Issue by etam** [almonit/almonit-plugin#22]
I added my local ipfs node as a gateway (name: localhost, url: `http://localhost:8080/`).

`almonit.eth` is redirecting to `https://http//localhost:8080///ipfs/QmZFz1n7iMoidyPRjaBC9ngPmb3jwp7qnSnes3DpNXZHL1/`

**Comment by etam** [comment]
I tried changing the url to just `localhost:8080` but it's not helping.

**Comment by etam** [comment]
Ok, I can use local node by entering it in "other" option. I think it's redundant with gateways list.

**Comment by eyalron33** [comment]
How about a clarification message if a user tries to add 'localhost' in the gateway list?

We actually intended first to allow 'localhost' as an option in the gateway list, but this resulted both in confused users and in complex code. 

Users confusion happened since a localhost is *not* a gateway. A gateway means accessing ipfs using a middleman, while localhost means you are part of the ipfs network. 

Code complexity happened since the business logic is different for both options. Gateways are accessed via https, while localhost uses http.  Gateways have the "random gateway" option to ensure that no gateway will become a monopoly. However, randomization makes no sense if you have localhost.

**Comment by etam** [comment]
Good points.

Another option is to have a separate "localhost" option, like in ethereum node selection.

When I installed this plugin I wanted to configure it to use my local ipfs node. I didn't know the difference between "gateways" list and "other" option. I assumed that if I remove all gateways and put localhost there, it should work as intended.

**Comment by etam** [comment]
I think that current tooltip is good enough.
