### ISSUE TITLE
Installing update cleared my settings

### ISSUE THREAD

**Issue by etam** [almonit/almonit-plugin#37]
I noticed that almonit has updated, because it automatically opened almonit.eth website. I think it should not do it, when updating.

But the main problem is that I had configured my own geth and ipfs nodes and after update those setting were reset to default.

Browser: Firefox 73.0.1

**Comment by eyalron33** [comment]
Both your remarks are noted. I'll fix them both this week.

**Comment by eyalron33** [comment]
[Fixed](https://github.com/almonit/almonit-plugin/commit/c06e1a08b1696f00f7105bf6fae8bb9f4e17d948).

**Comment by eyalron33** [comment]
I'm quickly reporting here that sadly - the new update also resets the settings. The reason is that we changed too much in the settings system (to make it more modular), and it became an impossible nightmare to migrate the old settings. 

I deeply apologize for that, I spent a long time trying to make it work turned out there were too many cases. I hope it won't happen in the next version update.
